# Generated by Django 5.1.3 on 2024-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_entrada_cantidad_alter_entrada_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
